add 3 phone methods
AmanoTeam/hydrogram pull request #39
Opened 2024-06-30 20:40 UTC by 2ei

- 1 : Add `create_group_call` and `discard_group_call` methods.
- 2 : Add `invite_group_call_members` method.

### Note:
- I already sent the same pr for pyrotgfork,  if you wanna take a look: ( [37](https://github.com/TelegramPlayGround/pyrogram/pull/37) )

2024-06-30 20:43 UTC, alissonlauffer commented on hydrogram/methods/phone/__init__.py
> +class Phone(CreateVideoChat, DiscardGroupCall):
Missing `InviteGroupCallMembers` here?

2024-06-30 20:43 UTC, 2ei commented on hydrogram/methods/phone/__init__.py
> +class Phone(CreateVideoChat, DiscardGroupCall):
ah i forgot to push it

2024-06-30 21:06 UTC, HitaloM requested changes
The code is well written and follows good practices, it only needs 2 small changes that I requested. Thank you! 😃

2024-06-30 21:06 UTC, HitaloM commented on hydrogram/methods/phone/discard_grou_call.py
> +#  Hydrogram - Telegram MTProto API Client Library for Python
Here the file has a typo in the name, it says discard_grou_call, instead of discard_group_call

2024-06-30 21:06 UTC, HitaloM commented on hydrogram/methods/phone/invite_group_call_members.py
> +#  Copyright (C) 2017-2023 Dan <https://github.com/delivrance>
You don't have to grant Dan the copyright to a file that wasn't part of Pyrogram before the rebranding to Hydrogram.

2024-11-16 03:40 UTC, alissonlauffer approved these changes

2024-11-16 03:40 UTC, merged